# Generated by Django 2.2 on 2019-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '展示'), (2, '隐藏')], default=1, verbose_name='状态'),
        ),
    ]
