# Generated by Django 2.2 on 2019-06-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_tiem',
            new_name='created_time',
        ),
    ]
